### PR TITLE
Add symfony 3.0 support

### PR DESCRIPTION
**Pull request by Ener-Getick**
This PR adds symfony 3.0 support.

### CODE REVIEW

**Comment by garak** [comment]
Thanks for your contribution!
Can I ask you more informations about travis configuration? You can write me to my personal email, that is my github nickname at gmail.

**Comment by Ener-Getick** [comment]
Of course, what would you like to know?

**Comment by garak** [comment]
I'm mainly interested in cache configuration, since I believed (likely erroneously)  that travis built every build on a new instance. If it's a too long explanation, pointing me to a doc would be fine. Thanks

**Comment by Ener-Getick** [comment]
You're right, this part only stores the cache for dependencies (composer, npm, ...) and for the specified folders not the build itself.
You should remove the line for pip, I don't know why I added it...

For more informations, you can read the [doc](http://docs.travis-ci.com/user/caching/).

**Pull request merged**
