### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by alexmatveev**

### CODE REVIEW

**Comment by garak** [comment]
Why?

**Comment by alexmatveev** [comment]
@garak fixed mistake in syntax

**Comment by garak** [comment]
Where is the mistake?

**Comment by alexmatveev** [comment]
` // for Symfony 3, use 'Beelab\Recaptcha2Bundle\Form\Type\RecaptchaType' instead of 'beelab_recaptcha2'

'Beelab\Recaptcha2Bundle\Form\Type\RecaptchaType' is wrong

**Comment by garak** [comment]
The output of `\Beelab\Recaptcha2Bundle\Form\Type\RecaptchaType::class` is exactly `Beelab\Recaptcha2Bundle\Form\Type\RecaptchaType`.
What's wrong?

**Comment by garak** [comment]
Closing for missing feedback

**Pull request closed without merging**
